import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/component/website/Header";
import Footer from "@/component/website/Footer";
import SearchBarSection from "@/component/website/SearchBarSection";
import StoreProvider from "@/component/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <Header />
          <SearchBarSection />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
