export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import StoreProvider from '@/component/StoreProvider'
import '../globals.css'


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>{children}</body>
      </StoreProvider>

    </html>
  )
}
