import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideMenu from "@/component/admin/SideMenu";
import Header from "@/component/admin/Header";
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="top-right"
          autoClose={1000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />

        {/* Fixed Sidebar */}
        <SideMenu />

        {/* Main Content: add margin-left same as sidebar width */}
        <div className="ml-64">
          <Header />
          <div className="p-4 bg-gray-100 min-h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
