import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideMenu from "@/component/admin/SideMenu";
import Header from "@/component/admin/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-5">
          <SideMenu />
          <div className="col-span-4">
            <Header />
            <div className="p-4 bg-gray-100 min-h-screen">
              {children}
            </div>

          </div>

        </div>



      </body>
    </html>
  );
}
